name: 'dbt_clickstream'
version: '1.0.0'
config-version: 2

# This MUST match the profile name defined in your ~/.dbt/profiles.yml
profile: 'clickstream_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  dbt_clickstream:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
