simulation:
  num_users: 1000
  output_dir: "local_clickstream_raw"

funnel:
  steps:
  - "view_homepage"
  - "search_product"
  - "view_product_details"
  - "add_to_cart"
  - "checkout_initiated"
  - "purchase_completed"

  transition_probabilities: #Conditional markov prob = n(S+1)/ n(S)
    view_homepage: 0.80
    search_product: 0.60
    view_product_details: 0.40
    add_to_cart: 0.50

experiments:
  experiment_name: "new_checkout_ui"
  checkout_conversion:
    control: 0.45
    variant: 0.70

