CREATE DATABASE IF NOT EXISTS CLICKSTREAM_DB;
CREATE SCHEMA IF NOT EXISTS CLICKSTREAM_DB.RAW;

USE DATABASE CLICKSTREAM_DB;
USE SCHEMA RAW;

-- landing table for raw semi-structured data
CREATE OR REPLACE TABLE CLICKSTREAM_EVENTS(
raw_payload VARIANT,
ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- json file format
CREATE OR REPLACE FILE FORMAT JSON_FILE_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = FALSE
    ENABLE_OCTAL = FALSE
    IGNORE_UTF8_ERRORS = TRUE;

-- external stage pointing to s3 bucket
CREATE OR REPLACE STAGE S3_CLICKSTREAM_STAGE
    URL = 's3://YOUR_S3_BUCKET/YOUR_PREFIX/'
    CREDENTIALS = (
        AWS_KEY_ID = 'YOUR_AWS_KEY_ID'
        AWS_SECRET_KEY = 'YOUR_AWS_SECRET_KEY'
    )
    FILE_FORMAT = JSON_FILE_FORMAT;

LIST @S3_CLICKSTREAM_STAGE;

-- Create snowpipe
CREATE OR REPLACE PIPE CLICKSTREAM_SNOWPIPE
    AUTO_INGEST = TRUE
    AS
    COPY INTO CLICKSTREAM_DB.RAW.CLICKSTREAM_EVENTS (raw_payload)
    FROM @CLICKSTREAM_DB.RAW.S3_CLICKSTREAM_STAGE;

SHOW PIPES;

-- manual load of 50K existing S3 JSON files into the landing table
COPY INTO CLICKSTREAM_DB.RAW.CLICKSTREAM_EVENTS (raw_payload)
FROM @CLICKSTREAM_DB.RAW.S3_CLICKSTREAM_STAGE;

--
SELECT COUNT(*) FROM CLICKSTREAM_DB.RAW.CLICKSTREAM_EVENTS;
--
SELECT * FROM CLICKSTREAM_DB.RAW.CLICKSTREAM_EVENTS;
--
SELECT SYSTEM$PIPE_STATUS('CLICKSTREAM_DB.RAW.CLICKSTREAM_SNOWPIPE');
--
SELECT COUNT(*) FROM CLICKSTREAM_DB.RAW.CLICKSTREAM_EVENTS;
